[versions]
agp = "9.3.2"
coroutines = "1.11.0"
firebase-bom = "34.18.0"
junit = "4.13.2"
json = "20250517"
ktor = "3.3.3"
koog = "1.1.1"
kotlin-logging = "8.0.01"
langchain4j = "1.19.0"
langchain4j-okhttp = "1.19.0-beta29"
okhttp = "5.3.0"
openai-kotlin = "4.1.0"
play-integrity = "1.6.0"
retrofit = "3.0.0"

[libraries]
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
junit = { module = "junit:junit", version.ref = "junit" }
json = { module = "org.json:json", version.ref = "json" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
koog-http-client-okhttp = { module = "ai.koog:http-client-okhttp", version.ref = "koog" }
koog-prompt-executor-openai = { module = "ai.koog:prompt-executor-openai-client", version.ref = "koog" }
koog-utils-jvm = { module = "ai.koog:utils-jvm", version.ref = "koog" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
langchain4j-http-client-okhttp = { module = "dev.langchain4j:langchain4j-http-client-okhttp", version.ref = "langchain4j-okhttp" }
langchain4j-open-ai = { module = "dev.langchain4j:langchain4j-open-ai", version.ref = "langchain4j" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
openai-kotlin = { module = "com.aallam.openai:openai-client", version.ref = "openai-kotlin" }
play-integrity = { module = "com.google.android.play:integrity", version.ref = "play-integrity" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
